from teapot.configs.runtime import SCRATCHPAD_SIZE


class ScratchpadSlots:
    FIRST_SPILL = SCRATCHPAD_SIZE // 2
    RISCV64_LANDING_RESTORE_FLAG = FIRST_SPILL + 4096
    RISCV64_LANDING_TEMP = RISCV64_LANDING_RESTORE_FLAG + 8
    RISCV64_ORIGINAL_TP = SCRATCHPAD_SIZE - 32768

    TEXT_DIFT_CAPTURE_SCRATCH_SAVE = SCRATCHPAD_SIZE - 65536
    TEXT_DIFT_LLVM_SCRATCH_SAVE = TEXT_DIFT_CAPTURE_SCRATCH_SAVE + 4096
    TEXT_DIFT_LLVM_ORIGINAL_SP_SLOT = 4096 - 8
    TEXT_DIFT_LLVM_STACK = TEXT_DIFT_LLVM_SCRATCH_SAVE + 8192
    TEXT_DIFT_LLVM_STACK_SIZE = 16384
    TEXT_DIFT_LLVM_STACK_SP = TEXT_DIFT_LLVM_STACK + TEXT_DIFT_LLVM_STACK_SIZE // 2


class AArch64ShadowStackSlots:
    # Keep this encodable as an AArch64 add/sub immediate.
    SIZE = 8 * 1024 * 1024
    DIFT = 0
    MEMLOG = 64
    ASAN = 128
    GADGET_MEM = 192
    GADGET_PORT = 240
    GADGET = GADGET_MEM
    COVERAGE = 288
    CONTROL = 320
    RESTORE = 352
    INDIRECT_TARGET = 384
    REPORT = 416
    ABI = 448
    TEXT_DIFT_CAPTURE = 480
    TEXT_DIFT_LLVM = 512


SCRATCHPAD_FIRST_SPILL_OFFSET = ScratchpadSlots.FIRST_SPILL
RISCV64_LANDING_RESTORE_FLAG_OFFSET = ScratchpadSlots.RISCV64_LANDING_RESTORE_FLAG
RISCV64_LANDING_TEMP_OFFSET = ScratchpadSlots.RISCV64_LANDING_TEMP
RISCV64_ORIGINAL_TP_OFFSET = ScratchpadSlots.RISCV64_ORIGINAL_TP

AARCH64_SHADOW_STACK_SIZE = AArch64ShadowStackSlots.SIZE
AARCH64_SHADOW_STACK_DIFT_OFFSET = AArch64ShadowStackSlots.DIFT
AARCH64_SHADOW_STACK_MEMLOG_OFFSET = AArch64ShadowStackSlots.MEMLOG
AARCH64_SHADOW_STACK_ASAN_OFFSET = AArch64ShadowStackSlots.ASAN
AARCH64_SHADOW_STACK_GADGET_MEM_OFFSET = AArch64ShadowStackSlots.GADGET_MEM
AARCH64_SHADOW_STACK_GADGET_PORT_OFFSET = AArch64ShadowStackSlots.GADGET_PORT
AARCH64_SHADOW_STACK_GADGET_OFFSET = AArch64ShadowStackSlots.GADGET
AARCH64_SHADOW_STACK_COVERAGE_OFFSET = AArch64ShadowStackSlots.COVERAGE
AARCH64_SHADOW_STACK_CONTROL_OFFSET = AArch64ShadowStackSlots.CONTROL
AARCH64_SHADOW_STACK_RESTORE_OFFSET = AArch64ShadowStackSlots.RESTORE
AARCH64_SHADOW_STACK_INDIRECT_TARGET_OFFSET = AArch64ShadowStackSlots.INDIRECT_TARGET
AARCH64_SHADOW_STACK_ABI_OFFSET = AArch64ShadowStackSlots.ABI
AARCH64_SHADOW_STACK_TEXT_DIFT_CAPTURE_OFFSET = AArch64ShadowStackSlots.TEXT_DIFT_CAPTURE
AARCH64_SHADOW_STACK_TEXT_DIFT_LLVM_OFFSET = AArch64ShadowStackSlots.TEXT_DIFT_LLVM
AARCH64_SHADOW_STACK_REPORT_OFFSET = AArch64ShadowStackSlots.REPORT
